#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

<<<<<<< HEAD
#define PROJECT_SOURCE_DIR "D:/cpsc427game/team08/"
=======
#define PROJECT_SOURCE_DIR "D:/学习/cpsc427game/team08/"
>>>>>>> a8c4472545551adb568fbb9db7522d62c921036c
